### ISSUE TITLE
[REQ] Remove the door.... thing.

### ISSUE THREAD

**Issue by kronflux** [d-rafferty/lethal-tube-removal#19]
I don't really know what to call it. but it's ugly and annoying. When you walk past it, you bump into it, it's a very minor inconvenience, but I hate it lol

![image](https://github.com/d-rafferty/lethal-tube-removal/assets/834451/0430afe5-a5f5-4a90-88a5-16a340b43678)

**Comment by d-rafferty** [comment]
I've just went and checked this out, and unfortunately that thing is baked into the model of the hull of the ship itself and anything that doesn't have it's own specific model cannot be removed due to not having access to the game's models. This has been the case with a few things people have wanted to remove. Sorry!
