### ISSUE TITLE
[Request] Remove Monitor with cam outside above door buttons.

### ISSUE THREAD

**Issue by andrzej2273** [d-rafferty/lethal-tube-removal#27]
I recently turned off the monitor displaying the camera image outside using OpenBodyCams and noticed a huge increase in FPS in the ship, but I couldn't find a mod to remove the monitor above the door buttons. Probably the fps in the ship could be even better. The option to remove the monitor above the buttons would be great

**Comment by d-rafferty** [comment]
I'll check in on this later today!

**Comment by d-rafferty** [comment]
Should be working in new patch v1.6.4 which will be pushed out today! Added in #30

**Comment by andrzej2273** [comment]
Thanks a lot, it works. When I look towards the ship door I have 120+ fps instead of 105.

**Comment by d-rafferty** [comment]
Fantastic, glad I could help!

**Comment by andrzej2273** [comment]
I have one more request. Could you make option to turn off monitor to the right of the radar. Because OpenBodyCams can be problematic.

**Comment by d-rafferty** [comment]
So, the bottom two large monitors are one singular object. I could add an option but it would have to remove both of them. If that's something you'd want I could add it no problem, but that's the only way I could do it.

**Comment by andrzej2273** [comment]
I wish the monitor stayed.  What I want is for the right monitor not to generate the image from the camera, as OpenBodyCams does.

**Comment by d-rafferty** [comment]
Yeah, I understand, unfortunately the scope of this mod doesn't extend as far as to be able to change outputs of the screens, but I may have an answer for you.

You might want to check out this project I have contributed a small bit to in the past. [OpenMonitors](https://github.com/julian-perge/LC_OpenMonitors)

It might be possible for you to use this and simply turn off the output of the monitors you don't want? I'm not sure if there will be conflicts, but it may possibly increase performance for you.

**Comment by andrzej2273** [comment]
Thanks, I will test this mod tommorow

**Comment by andrzej2273** [comment]
I updated the modpack today and noticed the spam log. There is some conflict with OpenBodyCams. What a coincidence. I did some tests and it only happens when I update LethalPipeRemoval from 1.6.4. When I downgrade back to 1.6.4 it still happens and I have to use backup of my modpack.
![openBez tytuł1111111111u](https://github.com/d-rafferty/lethal-tube-removal/assets/168291598/042dda16-25c0-4289-b031-99ca941671f0)

**Comment by andrzej2273** [comment]
BTW. This colored weather display from OpenMonitors is really nice. Thanks.

**Comment by d-rafferty** [comment]
Interesting.. are you sure its not conflicting with something else? Because I just tested it with LethalPipeRemoval v1.6.6 and didn't have any errors. (aside from the sound error you see that's unrelated)

![image](https://github.com/d-rafferty/lethal-tube-removal/assets/90558421/ea12c619-ada3-4443-8846-4579f56c75d9)

**Comment by andrzej2273** [comment]
Hmm I will do some tests later.

**Comment by andrzej2273** [comment]
I figured it out. I did new profile and when I delete door monitor it's happening.
![11111Bez t111111ytułu](https://github.com/d-rafferty/lethal-tube-removal/assets/168291598/fc816ea6-80ae-4774-a7b1-4d9b831bfc91)

**Comment by d-rafferty** [comment]
> I figured it out. I did new profile and when I delete door monitor it's happening. 

Yep I've found the error, and it seems to only occurs when a player is looking where the monitor used to be, because it is still trying to feed it info from the cameras and I believe all of the camera feeds may be interacting in some way here. I'll try to hack a workaround in but I'm not sure how it will go.

**Comment by d-rafferty** [comment]
SHOULD be fixed with #40 in v1.6.8

When removing the door monitor, I also had to remove the outside security cam to prevent it from trying to access the door monitor and thus conflicting with openbodycams. I just tested this and it was all running smoothly for me with no issues with the bodycams on. Let me know if it works for you!

**Comment by andrzej2273** [comment]
It works!! Now I don't even need to use OpenBOdyCams. When I test solo with combination of newest version of your mod and GeneralImprowments better monitors i squeezed outs 110- 120 fps on orbit and on moon 80-100 (it depends where you looking) which is huge improment. Thanks a lot.

**Comment by d-rafferty** [comment]
Glad I could help!
