### ISSUE TITLE
Suggestion!!! Allow setting the default position of the storage cabinet ^^

### ISSUE THREAD

**Issue by Lunxara** [d-rafferty/lethal-tube-removal#47]
So I was thinking it would be really cool to allow setting up the default position of the storage cabinet similar to the terminal, do you think you could add that as a feature? <3

**Comment by d-rafferty** [comment]
Yes this should be no problem. I have another request to set custom coordinates for a few other items as well so I will add the cabinet to the list and work on it in the next day or so!

**Comment by Lunxara** [comment]
> Yes this should be no problem. I have another request to set custom coordinates for a few other items as well so I will add the cabinet to the list and work on it in the next day or so!

Ty that'll be perfect!!! ^^

**Comment by d-rafferty** [comment]
Just went ahead and got this one done since it is the easiest on the list of requests at the moment lol. I also used a different method than some of the other custom coordinate options so it **_should_** be a bit more responsive and not send the shelf off into space if you change the rotation slightly..

Will be live in v1.7.2 - already pushed out, usually takes thunderstore about 10 minutes or so to have it available
